--EXERCÍCIOS FUNÇÕES  

CREATE FUNCTION SEMANA (@DIA DATE) RETURNS VARCHAR(20) AS  
BEGIN 
DECLARE @RESULTADO INT  
SELECT @RESULTADO =   DATEPART(WEEKDAY, @DIA)  
IF @RESULTADO = 1  
SET @RESULTADO = ‘DOMINGO’ 
IF @RESULTADO = 2 
SET @RESULTADO = ‘SEGUNDA’ 
IF @RESULTADO = 3 
SET @RESULTADO = ‘TERÇA-FEIRA’ 
IF @RESULTADO = 4 
SET @RESULTADO = ‘QUARTA-FEIRA’ 
IF @RESULTADO = 5 
SET @RESULTADO = ‘QUINTA-FEIRA’ 
IF @RESULTADO = 6 
SET @RESULTADO = ‘SEXTA-FEIRA’ 
IF @RESULTADO = 7 
SET @RESULTADO = ‘SÁBADO’ 

RETURN @RESULTADO 
END 
GO 

SELECT DBO.SEMANA(‘2025-06-05') AS DIA_SEMANA 

CREATE FUNCTION VERIFICAR (@NUMERO INT) RETURNS VARCHAR(5) AS  
BEGIN 
DECLARE @RESULTADO VARCHAR(5) 
IF (@NUMERO % 2) = 0 
SET @RESULTADO = ‘PAR’ 
IF (@NUMERO % 2) != 0 
SET @RESULTADO = ‘IMPAR’ 
RETURN @RESULTADO 
END 
GO 

SELECT DBO.VERIFICAR(12) AS ParImpar 


CREATE FUNCTION IDADE (@DATA DATE) RETURNS INT AS 
BEGIN 
DECLARE @RESULTADO INT 
SET @RESULTADO = floor(datediff(day, @DATA, getdate()) / 365.25) 
RETURN @RESULTADO 
END 
GO 

SELECT DBO.IDADE(‘2006-02-12') AS IDADE 

4 – CREATE FUNCTION CONTAR (@PALAVRA VARCHAR(30)) RETURNS INT AS 
BEGIN 
DECLARE @CONTADOR INT 
SET @CONTADOR = LEN(@PALAVRA) 
RETURN @CONTADOR  
END 
GO 

SELECT DBO.CONTAR(‘CENTRO UNIVERSITÁRIO UNISATC’) AS QTDE 

5 - CREATE FUNCTION DIAS (@DATA1 DATE, @DATA2 DATE) RETURNS INT AS 
BEGIN 
DECLARE @RESULTADO INT 
SET @RESULTADO = datediff(day, @DATA1, @DATA2)  
RETURN @RESULTADO 
END 
GO 

SELECT DBO.DIAS(‘2023-05-09', ‘2023-05-15') AS QTDE_DIAS 

CREATE FUNCTION SINISTROS (@PLACA VARCHAR(9)) RETURNS INT AS 
BEGIN 
DECLARE @RESULTADO INT 
SELECT @RESULTADO = COUNT(cod_sinistro) 
         FROM SINISTRO 
         WHERE PLACA = @PLACA 
RETURN @RESULTADO  
END 
GO 

SELECT *, DBO.SINISTROS(PLACA) AS QTDE_SINISTRO 
FROM SINISTRO 

CREATE FUNCTION CONTAR(@COD_CLIENTE INT) RETURNS INT AS 
BEGIN   
DECLARE @RESULTADO INT 
SELECT @RESULTADO = COUNT(cod_apolice) 
FROM APOLICE 
WHERE DT_FIM_VIGENCIA < GETDATE() AND CD_CLIENTE = @COD_CLIENTE 
RETURN @RESULTADO 
END 
GO 

SELECT *, DBO.CONTAR(CD_CLIENTE) AS QTDE_APOLICE_VENCIDA 
FROM CLIENTE 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
