--EXERCÍCIO DE FIXAÇÃO + REVISÃO PROVA  

SELECT CURSO.NM_CURSO, COUNT(ALUNO.CD_ALUNO) 

FROM CURSO  

LEFT JOIN ALUNO 

ON CURSO.CD_CURSO = ALUNO.CD_CURSO 

GROUP BY CURSO.NM_CURSO 

ORDER BY COUNT(ALUNO.CD_ALUNO) DESC 

SELECT * 
FROM CARRO 
WHERE PLACA IN ( SELECT PLACA  
          FROM APOLICE 
          WHERE DATA_FIM_VIGENCIA >= GETDATE()) 

SELECT ESTADO.NM_ESTADO, COUNT(MUNICIPIO,CD_MUNICIPIO) AS QTDE 
FROM ESTADO 
INNER JOIN MUNICIPIO 
ON ESTADO.CD_ESTADO = MUNICIPIO.CD_MUNICIPIO 
GROUP BY ESTADO.NM_ESTADO  
HAVING COUNT(MUNICIPIO,CD_MUNICIPIO)  > 200 
ORDER BY COUNT(MUNICIPIO,CD_MUNICIPIO) DESC 

SELECT *, ROW_NUMBER() OVER(ORDER BY DATA_SNISTRO,HORA_SNISTRO ASC) AS NR_SEQ 
FROM SINISTRO 

WITH CTE AS ( 
SELECT MODALIDADE, NOME_ATLETA, TEMPO, DENSE_RANK() OVER(PARTITION BY MODALIDADE ORDER BY TEMPO ASC) AS RANK 
FROM RESULTADO_NATACAO 
WHERE DATA_COMPETICAO = ‘2023-09-17') 
SELECT * 
FROM CTE 
WHERE RANK <= 3; 

CREATE NONCLUSTERED INDEX ID1 ON RESULTADO_NATACAO (DATA_COMPETICAO) INCLUDE (MODALIDADE, NOME_ATLETA, TEMPO); 

SELECT AGENDA.COD_AGENDA, PACIENTE.NM_PACIENTE, PROFISSIONAL.NM_PREOFISSIONAL, AGENDA.DT_INICIO, AGENDA.DT_FIM 
FROM PACIENTE 
INNER JOIN AGENDA 
ON PACIENTE.CD_PACIENTE = AGENDA.CD_PACIENTE 
INNER JOIN PROFISSIONAL  
ON AGENDA.CD_PROFISSIONAL = PROFISSIONAL.CD_PROFISSIONAL  
WHERE AGENDA.DT_INICIO BETWEEN (‘2020-01-01' AND ‘2020-12-31') AND AGENDA.DT_FIM BETWEEN (‘2020-01-01' AND ‘2020-12-31') 
ORDER BY AGENDA.DT_INICIO ASC 

SELECT NM_PROFISSIONAL 
FROM PROFISSIONAL 
WHERE NOT EXISTS (SELECT CD_PROFISSIONAL 
FROM AGENDA 
WHERE (AGENDA.CD_PROFISSIONAL = PROFISSIONAL.CD_PROFISSIONAL) AND DT_INICIO BETWEEN ‘2021-01-01' AND ‘2021-12-31') 

SELECT PROFISSIONAL.NM_PROFISSIONAL  
FROM PROFISSIONAL 
LEFT JOIN AGENDA 
ON PROFISSIONAL.CD_PROFISSIONAL = AGENDA.CD_PROFISSIONAL 
WHERE AGENDA.CD_AGENDA IS NULL 

--TRANSAÇÕES SÃO OPERAÇÕES QUE MODIFICAM OS DADOS SELECINADOS, ALTERANDO NOME, INCLUINDO OUTROS DADOS OU AFETANDO VALORES. É IMPORTANTE MANTER O CONTROLE DE CONCORRÊNCIA PARA OUTRA PESSOA NÃO CONSIGUIR LER OU ALTERAR O DADO QUE ESTÁ EM ESTADO TRANSITÓRIO.  

--V, V, F, F, V 

--ELE MELHORA A PERFORMANCE DE CONSULTAS POIS PERMITE QUE OS DADOS SEJAM ORGANIZADOS E ‘PROCURADOS’ DE MANEIRA MAIS DIRETA. JÁ EM BLOQUEIOS DE CONCORRÊNCIA, que as transações acessem apenas as partes relevantes dos dados solicitados. 

--V, V, V, V, V 

--F, F, V, F, V, F 



 
