WITH CTE AS ( 
    SELECT PLACA, COUNT(PLACA) AS qtd 
    FROM SINISTRO 
    GROUP BY PLACA) 
SELECT TOP 1 * 
FROM CTE 
ORDER BY qtd DESC; 

SELECT NOME 
FROM CLIENTE  
WHERE NOME LIKE ‘%A%’ AND NOME NOT LIKE ‘%A’ 

SELECT CLIENTE.NOME 
FROM CLIENTE  
LEFT JOIN APOLICE 
ON CLIENTE.COD_CLIENTE = APOLICE.COD_CLIENTE 
WHERE APOLICE.COD_CLIENTE IS NULL 

SELECT NOME  
FROM CLIENTE  
WHERE CD_CLIENTE NOT IN ( SELECT CD_CLIENTE  
        FROM APOLICE) 

SELECT CARRO.PLACA 
FROM CARRO  
LEFT JOIN APOLICE 
ON CARRO.PLACA = APOLICE.PLACA 
WHERE APOLICE.COD_APOLICE IS NULL 

SELECT PLACA 
FROM CARRO 
WHERE PLACA NOT IN (SELECT PLACA  
      FROM APOLICE) 

SELECT NOME  
FROM CLIENTE  


SELECT PLACA  
FROM CARRO 
WHERE PLACA LIKE ‘L%’ OR PLACA LIKE ‘M%’ 

SELECT * 
FROM SINISTRO  
WHERE DATA_SINISTRO BETWEEN ‘2022-01-01' AND ‘2022-12-31' 

WITH CTE AS ( 
SELECT * 
FROM CLIENTE  
WHERE TELEFONE_FIXO IS NULL AND TELEFONE_CELULAR IS NULL) 
SELECT *  
FROM CTE 

SELECT CLIENTE.* 
FROM CLIENTE  
INNER JOIN APOLICE 
ON CLIENTE.COD_CLIENTE = APOLICE.COD_CLIENTE 
WHERE APOLICE.DATA_FIM_VIGENCIA  <  GETDATE() 

SELECT *  
FROM CLIENTE  
WHERE COD_CLIENTE IN (SELECT COD_CLIENTE 
            FROM APOLICE 
            WHERE DATA_FIM_VIGENCIA < GETDATE())  

SELECT PLACA,  
FROM SINISTRO  
INNER JOIN APOLICE  
ON SINISTRO.PLACA = APOLICE.PLACA 
WHERE SINISTRO.DATA_SINISTRO > APOLICE.DATA_FIM_VIGENCIA 

SELECT PLACA  
FROM SINISTRO 
WHERE EXISTS (SELECT PLACA 
         FROM APOLICE 
          WHERE APOLICE.PLACA = SINISTRO.PLACA AND 
 (APOLICE.DATA_FIM_VIGENCIA < SINISTRO.DATA_SINISTRO)) 

SELECT COUNT(CD_REGIAO) 
FROM REGIAO 
SELECT COUNT(CD_ESTADO) 
FROM ESTADO 

SELECT COUNT(CD_MUNICIPIO) 
FROM MUNICIPIO 

SELECT ESTADO.NOME, COUNT(MUNICIPIO.CD_MUNICIPIO) 
FROM ESTADO  
INNER JOIN MUNICIPIO 
ON ESTADO. CD_ESTADO = MUNICIPIO.CD_ESTADO 
GROUP BY ESTADO.NOME 

SELECT MUNICIPIO.NM_MUNICIPIO 
FROM MUNICIPIO 
INNER JOIN ESTADO 
ON MUNICIPIO.CD_ESTADO = ESTADO.CD_ESTADO 
INNER JOIN REGIAO 
ON ESTADO.CD_REGIAO = REGIAO.CD_REGIAO 
WHERE REGIAO.NM_REGIAO = ‘SUL’ 

SELECT MUNICIPIO.NM_MUNICIPIO 
FROM MUNICIPIO 
INNER JOIN ESTADO 
ON MUNICIPIO.CD_ESTADO = ESTADO.CD_ESTADO 
INNER JOIN REGIAO 
ON ESTADO.CD_REGIAO = REGIAO.CD_REGIAO 
WHERE REGIAO.NM_REGIAO = ‘SUL’ AND MUNICIPIO.NM_MUNICIPIO LIKE ‘C%’ 

SELECT * 
FROM MUNICIPIO  
WHERE LEN(NM_MUNICIPIO) > 10 

SELECT MUNICIPIO.NM_MUNICIPIO 
FROM MUNICIPIO 
INNER JOIN ESTADO 
ON MUNICIPIO.CD_ESTADO = ESTADO.CD_ESTADO 
INNER JOIN REGIAO 
ON ESTADO.CD_REGIAO = REGIAO.CD_REGIAO 
WHERE REGIAO.NM_REGIAO = ‘NORTE’ 

SELECT REGIAO.NM_REGIAO, COUNT(MUNICIPIO.CD_MUNICIPIO) 
FROM REGIAO 
INNER JOIN ESTADO 
ON ESTADO.CD_REGIAO = REGIAO.CD_REGIAO 
INNER JOIN MUNICIPIO 
ON MUNICIPIO.CD_ESTADO = ESTADO.CD_ESTADO 
GROUP BY REGIAO.NM_REGIAO 
HAVING REGIAO.NM_REGIAO LIKE ‘S%’ 

SELECT COUNT(CD_AVALIACAO) 
FROM AVALIACAO 

SELECT ALUNO.NM_ALUNO 
FROM ALUNO 
INNER JOIN AVALIACAO_ALUNO 
ON ALUNO.CD_ALUNO = AVALIACAO_ALUNO.CD_ALUNO 
WHERE AVALIACAO_ALUNO.DT_FIM_ IS NOT NULL 

SELECT * 
FROM ALUNO 
WHERE CD_ALUNO IN (SELECT CD_ALUNO 
     FROM AVALIACAO_ALUNO 
     WHERE DT_FIM IS NOT NULL) 

SELECT QUESTAO.* 
FROM QUESTAO 
INNER JOIN AVALIACAO 
ON AVALIAO.CS_AVALIACAO = QUESTAO.CD_AVALIACAO 
WHERE QUESTAO.TP_QUESTAO = 1 AND AVALIACAO.DS_AVALIAO LIKE ‘2A%’ 

SELECT QUESTAO.* 
FROM QUESTAO 
WHERE CD_AVALIACAO IN ( SELECT CD_AVALIACAO 
    	              FROM AVALIACAO 
WHERE DS_AVALIACAO LIKE ‘2A’) AND TP_QUESTAO = 1 

with cte as ( 
  SELECT ds_avaliacao, questao.cd_questao, ds_questao, COUNT(1) as qtde_alternativas 
  FROM avaliacao INNER JOIN questao ON avaliacao.cd_avaliacao = questao.cd_avaliacao 
  	   INNER JOIN questao_item ON questao.cd_questao = questao_item.cd_questao 
  GROUP BY ds_avaliacao, questao.cd_questao, ds_questao 
) 
select * from cte where qtde_alternativas > 4 
